import{initializeApp,getApps,getApp}from"https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js";
import{getFirestore,collection,addDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js";
import{firebaseConfig}from"./firebase-config.js";
const app=getApps().length?getApp():initializeApp(firebaseConfig);
const db=getFirestore(app);
const itemsElement=document.getElementById("cart-items");
const countElement=document.getElementById("cart-count");
const subtotalElement=document.getElementById("subtotal");
const totalElement=document.getElementById("total-price");
const checkoutForm=document.getElementById("checkout-form");
const checkoutButton=document.getElementById("place-order");
const errorElement=document.getElementById("checkout-error");
const successElement=document.getElementById("checkout-success");
const removeModal=new bootstrap.Modal(document.getElementById("remove-modal"));
let cart=[];
let productToRemove=null;
const formatMoney=value=>Number(value||0).toLocaleString("vi-VN")+"đ";
const getFinalPrice=item=>Number(item.finalPrice??Math.round(Number(item.price||0)*(1-Math.min(Math.max(Number(item.discount||0),0),100)/100)));
const escapeHtml=value=>String(value??"").replace(/[&<>'\"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[char]));
const readLocal=(...keys)=>{for(const key of keys){try{const data=JSON.parse(localStorage.getItem(key)||"null");if(data)return data;}catch(error){}}return null;};
function getUser(){const users=["current_user","current_users","currentUser"].map(key=>readLocal(key)).filter(Boolean).map(user=>({...user,uid:user.uid||user.userId||user.id||""}));return users.find(user=>user.uid&&user.email)||users.find(user=>user.email)||null;}
function loadCart(){const stored=readLocal("cart");cart=Array.isArray(stored)?stored:[];renderCart();}
function saveCart(){localStorage.setItem("cart",JSON.stringify(cart));}
function cartTotal(){return cart.reduce((total,item)=>total+getFinalPrice(item)*Number(item.quantity||0),0);}
function renderCart(){const quantity=cart.reduce((total,item)=>total+Number(item.quantity||0),0);countElement.textContent=`${quantity} sản phẩm`;const total=cartTotal();subtotalElement.textContent=formatMoney(total);totalElement.textContent=formatMoney(total);const totalButton=document.getElementById("button-total");if(totalButton)totalButton.textContent=formatMoney(total);checkoutButton.disabled=!cart.length;if(!cart.length){itemsElement.innerHTML=`<div class="empty-cart"><i class="bi bi-cart-x"></i><h2>Giỏ hàng đang trống</h2><p>Hãy chọn vài sản phẩm yêu thích để bắt đầu mua sắm.</p><a href="products.html">Khám phá sản phẩm</a></div>`;return;}itemsElement.innerHTML="";cart.forEach(item=>itemsElement.append(createItem(item)));}
function createItem(item){const price=getFinalPrice(item);const stock=Math.max(Number(item.amount||1),1);const quantity=Math.min(Math.max(Number(item.quantity||1),1),stock);item.quantity=quantity;const element=document.createElement("article");element.className="cart-item";element.innerHTML=`<div class="cart-item-image"><img src="${escapeHtml(item.image||"https://placehold.co/300x300/f5f5f5/777?text=ShopNow")}" alt="${escapeHtml(item.name||"Sản phẩm")}"></div><div class="cart-item-detail"><h2 class="cart-item-name">${escapeHtml(item.name||"Sản phẩm ShopNow")}</h2><div class="cart-item-price">${formatMoney(price)}${Number(item.discount||0)>0?` <span class="cart-item-original">${formatMoney(item.price)}</span>`:""}</div></div><div class="quantity-control"><button type="button" class="decrease" ${quantity<=1?"disabled":""} aria-label="Giảm số lượng"><i class="bi bi-dash"></i></button><span>${quantity}</span><button type="button" class="increase" ${quantity>=stock?"disabled":""} aria-label="Tăng số lượng"><i class="bi bi-plus"></i></button></div><strong class="cart-item-total">${formatMoney(price*quantity)}</strong><button type="button" class="remove-item" aria-label="Xóa sản phẩm"><i class="bi bi-trash3"></i></button>`;element.querySelector("img").addEventListener("error",event=>event.currentTarget.src="https://placehold.co/300x300/f5f5f5/777?text=ShopNow");element.querySelector(".decrease").addEventListener("click",()=>changeQuantity(item.id,-1));element.querySelector(".increase").addEventListener("click",()=>changeQuantity(item.id,1));element.querySelector(".remove-item").addEventListener("click",()=>askRemove(item));return element;}
function changeQuantity(id,amount){const item=cart.find(product=>String(product.id)===String(id));if(!item)return;item.quantity=Math.min(Math.max(Number(item.quantity||1)+amount,1),Math.max(Number(item.amount||1),1));saveCart();renderCart();}
function askRemove(item){productToRemove=item;document.getElementById("remove-modal-text").textContent=`"${item.name||"Sản phẩm này"}" sẽ được xóa khỏi giỏ hàng.`;removeModal.show();}
function removeProduct(){if(!productToRemove)return;cart=cart.filter(item=>String(item.id)!==String(productToRemove.id));productToRemove=null;saveCart();renderCart();removeModal.hide();}
function displayUser(){const user=getUser();document.getElementById("customer-name").textContent=user?.username||"Chưa đăng nhập";document.getElementById("customer-email").textContent=user?.email||"Chưa cập nhật";document.getElementById("customer-phone").textContent=user?.phone||"Chưa cập nhật";}
function selectPayment(){const isCard=document.querySelector('input[name="payment-method"]:checked').value==="card";document.querySelectorAll(".payment-option").forEach(option=>option.classList.toggle("active",option.querySelector("input").checked));document.getElementById("card-fields").classList.toggle("d-none",!isCard);["card-number","card-holder","card-expiry"].forEach(id=>document.getElementById(id).required=isCard);}
function setError(message){errorElement.textContent=message;errorElement.classList.remove("d-none");successElement.classList.add("d-none");}
function clearMessage(){errorElement.classList.add("d-none");successElement.classList.add("d-none");}
function validatePayment(){const address=document.getElementById("shipping-address");const method=document.querySelector('input[name="payment-method"]:checked').value;let valid=true;address.classList.toggle("is-invalid",!address.value.trim());valid=Boolean(address.value.trim());if(method==="card"){const number=document.getElementById("card-number");const holder=document.getElementById("card-holder");const expiry=document.getElementById("card-expiry");const validNumber=/^\d{16,19}$/.test(number.value.replace(/\s/g,""));const validHolder=holder.value.trim().length>=3;const matched=expiry.value.match(/^(0[1-9]|1[0-2])\/(\d{2})$/);const validExpiry=Boolean(matched)&&Number(`20${matched[2]}`)>new Date().getFullYear()-1;number.classList.toggle("is-invalid",!validNumber);holder.classList.toggle("is-invalid",!validHolder);expiry.classList.toggle("is-invalid",!validExpiry);valid=valid&&validNumber&&validHolder&&validExpiry;}return valid;}
function paymentData(){const method=document.querySelector('input[name="payment-method"]:checked').value;if(method==="cod")return{method:"COD",label:"Thanh toán khi nhận hàng"};const digits=document.getElementById("card-number").value.replace(/\s/g,"");return{method:"CARD",label:"Thẻ ngân hàng",cardLast4:digits.slice(-4),cardHolder:document.getElementById("card-holder").value.trim()};}
async function placeOrder(event){event.preventDefault();clearMessage();if(!cart.length){setError("Giỏ hàng đang trống, chưa thể đặt đơn.");return;}const user=getUser();if(!user?.email){setError("Không tìm thấy email đăng nhập. Vui lòng đăng nhập lại để đặt hàng.");return;}if(!user.uid){setError("Phiên đăng nhập chưa có UID. Vui lòng đăng xuất rồi đăng nhập lại.");return;}if(!validatePayment()){setError("Vui lòng kiểm tra lại các thông tin bắt buộc.");return;}checkoutButton.disabled=true;checkoutButton.innerHTML='<span class="spinner-border spinner-border-sm"></span> Đang tạo đơn hàng...';try{const order={user:{uid:user.uid,email:user.email,username:user.username||"",phone:user.phone||"",address:document.getElementById("shipping-address").value.trim()},products:cart.map(item=>({...item,quantity:Number(item.quantity||1),finalPrice:getFinalPrice(item)})),total:cartTotal(),payment:paymentData(),note:document.getElementById("order-note").value.trim(),status:"Pending",createdAt:serverTimestamp(),createdAtISO:new Date().toISOString()};const docRef=await addDoc(collection(db,"orders"),order);cart=[];saveCart();renderCart();successElement.textContent=`Đặt hàng thành công. Mã đơn hàng: ${docRef.id}`;successElement.classList.remove("d-none");checkoutForm.reset();selectPayment();}catch(error){console.error(error);setError(error.code==="permission-denied"?"Không có quyền tạo đơn hàng. Vui lòng kiểm tra Firestore Rules.":"Đặt hàng thất bại. Vui lòng kiểm tra kết nối và thử lại.");}finally{checkoutButton.disabled=!cart.length;checkoutButton.innerHTML=`<i class="bi bi-bag-check"></i> Đặt hàng <span id="button-total">${formatMoney(cartTotal())}</span>`;}}
document.getElementById("confirm-remove").addEventListener("click",removeProduct);
document.querySelectorAll('input[name="payment-method"]').forEach(input=>input.addEventListener("change",selectPayment));
document.getElementById("card-number").addEventListener("input",event=>event.target.value=event.target.value.replace(/\D/g,"").replace(/(.{4})/g,"$1 ").trim());
document.getElementById("card-expiry").addEventListener("input",event=>event.target.value=event.target.value.replace(/\D/g,"").replace(/(\d{2})(\d)/,"$1/$2").slice(0,5));
document.getElementById("checkout-scroll").addEventListener("click",()=>document.getElementById("checkout").scrollIntoView({behavior:"smooth",block:"start"}));
checkoutForm.addEventListener("submit",placeOrder);
displayUser();
selectPayment();
loadCart();
