import{initializeApp,getApps,getApp}from"https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js";
import{getFirestore,collection,getDocs,query,where,updateDoc,doc}from"https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js";
import{firebaseConfig}from"./firebase-config.js";
const app=getApps().length?getApp():initializeApp(firebaseConfig);
const db=getFirestore(app);
const list=document.getElementById("orders-list");
const message=document.getElementById("orders-message");
const modal=new bootstrap.Modal(document.getElementById("cancel-order-modal"));
let orders=[];
let activeFilter="all";
let cancellingId="";
const money=value=>Number(value||0).toLocaleString("vi-VN")+"đ";
const escapeHtml=value=>String(value??"").replace(/[&<>'\"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[char]));
const readLocal=key=>{try{return JSON.parse(localStorage.getItem(key)||"null");}catch(error){return null;}};
function getUser(){const users=["currentUser","current_user","current_users"].map(readLocal).filter(Boolean).map(user=>({...user,uid:user.uid||user.userId||user.id||""}));return users.find(user=>user.uid)||null;}
function getDate(order){const value=order.createdAt?.toDate?.()||order.createdAtISO||order.createdAt;const date=value instanceof Date?value:new Date(value);return Number.isNaN(date.getTime())?"Chưa cập nhật thời gian":date.toLocaleString("vi-VN",{dateStyle:"short",timeStyle:"short"});}
function finalPrice(product){return Number(product.finalPrice??Math.round(Number(product.price||0)*(1-Math.min(Math.max(Number(product.discount||0),0),100)/100)));}
function statusClass(status){const value=String(status||"Pending").toLowerCase();return value.includes("cancel")?"cancelled":value.includes("complete")||value.includes("deliver")?"complete":"";}
function showMessage(text){message.textContent=text;message.classList.remove("d-none");}
function clearMessage(){message.classList.add("d-none");}
function updateCounts(){const pending=orders.filter(order=>order.status==="Pending").length;const cancelled=orders.filter(order=>String(order.status||"").toLowerCase().includes("cancel")).length;document.getElementById("count-all").textContent=orders.length;document.getElementById("count-pending").textContent=pending;document.getElementById("count-cancelled").textContent=cancelled;document.getElementById("count-other").textContent=orders.length-pending-cancelled;}
function visibleOrders(){return orders.filter(order=>activeFilter==="all"?true:activeFilter==="other"?!["Pending","Cancelled"].includes(order.status):activeFilter===order.status);}
function productHtml(product){const price=finalPrice(product);const original=Number(product.price||0);return `<article class="order-product"><div class="order-product-image"><img src="${escapeHtml(product.image||"https://placehold.co/160x160/f5f5f5/777?text=ShopNow")}" alt="${escapeHtml(product.name||"Sản phẩm ShopNow")}"></div><div><h2>${escapeHtml(product.name||"Sản phẩm ShopNow")}</h2><p>${escapeHtml(product.distributor||"")} ${product.quantity?`• x${Number(product.quantity)}`:""}</p></div><div class="order-product-price">${original>price?`<del>${money(original)}</del>`:""}${money(price)}<small>${Number(product.quantity||1)} sản phẩm</small></div></article>`;}
function orderHtml(order){const products=Array.isArray(order.products)?order.products:[];const shown=products.slice(0,3);const info=order.user||{};const payment=order.payment||{};const canCancel=order.status==="Pending";return `<article class="order-card" data-order-id="${escapeHtml(order.id)}"><div class="order-top"><div class="order-code"><i class="bi bi-receipt"></i><div><span>Đơn hàng #${escapeHtml(order.id)}</span><span class="order-date">${getDate(order)}</span></div></div><span class="order-status ${statusClass(order.status)}">${escapeHtml(order.status||"Pending")}</span></div>${shown.map(productHtml).join("")}${products.length>3?`<div class="order-more">Và ${products.length-3} sản phẩm khác</div>`:""}<div class="order-extra"><div><strong>Người nhận</strong>${escapeHtml(info.username||"Chưa cập nhật")} · ${escapeHtml(info.phone||"Chưa cập nhật")}</div><div><strong>Địa chỉ giao hàng</strong>${escapeHtml(info.address||"Chưa cập nhật")}</div><div><strong>Thanh toán</strong>${escapeHtml(payment.label||payment.method||"Chưa cập nhật")}${order.note?`<br>Ghi chú: ${escapeHtml(order.note)}`:""}</div></div><div class="order-bottom"><div class="order-info"><span><i class="bi bi-box-seam"></i>${products.length} sản phẩm</span><span><i class="bi bi-envelope"></i>${escapeHtml(info.email||"Chưa cập nhật email")}</span></div><div class="order-total"><span>Thành tiền:</span><strong>${money(order.total)}</strong><div class="order-actions"><button class="order-detail-btn" type="button"><i class="bi bi-info-circle"></i> Chi tiết</button>${canCancel?`<button class="cancel-order-btn" type="button"><i class="bi bi-x-circle"></i> Hủy đơn</button>`:""}</div></div></div></article>`;}
function render(){const filtered=visibleOrders();updateCounts();if(!filtered.length){const text=orders.length?"Không có đơn hàng ở trạng thái này.":"Bạn chưa có đơn hàng nào.";list.innerHTML=`<div class="orders-empty"><i class="bi bi-bag-x"></i><h2>${text}</h2><p>${orders.length?"Hãy thử chọn một trạng thái khác.":"Khám phá sản phẩm yêu thích và bắt đầu mua sắm nhé."}</p>${orders.length?"":'<a href="products.html">Khám phá sản phẩm</a>'}</div>`;return;}list.innerHTML=filtered.map(orderHtml).join("");list.querySelectorAll("img").forEach(image=>image.addEventListener("error",()=>image.src="https://placehold.co/160x160/f5f5f5/777?text=ShopNow"));list.querySelectorAll(".order-detail-btn").forEach(button=>button.addEventListener("click",()=>{const extra=button.closest(".order-card").querySelector(".order-extra");extra.classList.toggle("show");button.innerHTML=extra.classList.contains("show")?'<i class="bi bi-chevron-up"></i> Thu gọn':'<i class="bi bi-info-circle"></i> Chi tiết';}));list.querySelectorAll(".cancel-order-btn").forEach(button=>button.addEventListener("click",()=>{cancellingId=button.closest(".order-card").dataset.orderId;modal.show();}));}
async function loadOrders(){clearMessage();list.innerHTML='<div class="orders-loading"><span class="spinner-border"></span><p>Đang tải đơn hàng của bạn...</p></div>';const user=getUser();if(!user?.uid){orders=[];showMessage("Không tìm thấy phiên đăng nhập. Vui lòng đăng nhập để xem đơn hàng.");render();return;}try{const snapshot=await getDocs(query(collection(db,"orders"),where("user.uid","==",user.uid)));orders=snapshot.docs.map(item=>({id:item.id,...item.data()})).sort((a,b)=>new Date(b.createdAtISO||0)-new Date(a.createdAtISO||0));render();}catch(error){console.error(error);orders=[];showMessage(error.code==="permission-denied"?"Bạn không có quyền xem đơn hàng này. Vui lòng kiểm tra Firestore Rules.":"Không thể tải đơn hàng. Vui lòng kiểm tra kết nối và thử lại.");render();}}
async function cancelOrder(){if(!cancellingId)return;const button=document.getElementById("confirm-cancel-order");button.disabled=true;button.innerHTML='<span class="spinner-border spinner-border-sm"></span> Đang hủy...';try{await updateDoc(doc(db,"orders",cancellingId),{status:"Cancelled"});const order=orders.find(item=>item.id===cancellingId);if(order)order.status="Cancelled";modal.hide();render();}catch(error){console.error(error);showMessage(error.code==="permission-denied"?"Bạn không có quyền hủy đơn hàng này.":"Không thể hủy đơn hàng. Vui lòng thử lại.");}finally{button.disabled=false;button.textContent="Xác nhận hủy";cancellingId="";}}
document.getElementById("orders-filter").addEventListener("click",event=>{const button=event.target.closest("button[data-status]");if(!button)return;activeFilter=button.dataset.status;document.querySelectorAll("#orders-filter button").forEach(item=>item.classList.toggle("active",item===button));render();});
document.getElementById("orders-refresh").addEventListener("click",loadOrders);
document.getElementById("confirm-cancel-order").addEventListener("click",cancelOrder);
loadOrders();
