import{initializeApp,getApps,getApp}from"https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js";
import{getFirestore,collection,getDocs}from"https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js";
import{firebaseConfig}from"./firebase-config.js";
const app=getApps().length?getApp():initializeApp(firebaseConfig);
const db=getFirestore(app);
const grids={hot:document.getElementById("hot-grid"),new:document.getElementById("new-grid"),sale:document.getElementById("sale-grid")};
const toast=document.getElementById("cart-toast");
const toastMessage=document.getElementById("cart-toast-message");
let toastTimer;
const formatPrice=value=>Number(value||0).toLocaleString("vi-VN")+"đ";
const finalPrice=product=>Math.round(Number(product.price||0)*(1-Math.min(Math.max(Number(product.discount||0),0),100)/100));
const escapeHtml=value=>String(value??"").replace(/[&<>'\"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[char]));
const getCart=()=>{try{return JSON.parse(localStorage.getItem("cart")||"[]");}catch(error){return [];}};
function showState(message,type="loading"){Object.values(grids).forEach(grid=>grid.innerHTML=`<div class="product-state ${type}"><i class="bi bi-${type==="error"?"exclamation-circle":"arrow-repeat"}"></i>${message}</div>`);}
function createCard(product){const stock=Number(product.amount||0);const discount=Math.max(Number(product.discount||0),0);const image=product.image||"https://placehold.co/600x600/f5f5f5/777?text=ShopNow";const name=product.name||"Sản phẩm ShopNow";const price=finalPrice(product);const card=document.createElement("article");card.className="home-product-card";card.innerHTML=`<div class="home-product-image"><img src="${escapeHtml(image)}" alt="${escapeHtml(name)}" loading="lazy"><span class="discount-badge" ${discount?"":"hidden"}>-${discount}%</span><span class="stock-badge">${stock>0?`Còn ${stock} sản phẩm`:"Tạm hết hàng"}</span></div><div class="home-product-content"><span class="home-product-seller"><i class="bi bi-shop"></i> ${escapeHtml(product.distributor||"ShopNow")}</span><h3 class="home-product-name">${escapeHtml(name)}</h3><p class="home-product-description">${escapeHtml(product.description||"Sản phẩm chất lượng với ưu đãi hấp dẫn.")}</p><strong class="home-product-price">${formatPrice(price)}</strong><span class="home-product-original ${discount?"":"empty"}">${formatPrice(product.price)}</span><button class="home-add-cart" type="button" ${stock>0?"":"disabled"}><i class="bi bi-cart-plus"></i> ${stock>0?"Thêm vào giỏ":"Hết hàng"}</button></div>`;card.querySelector("img").addEventListener("error",event=>event.currentTarget.src="https://placehold.co/600x600/f5f5f5/777?text=ShopNow");card.querySelector("button").addEventListener("click",()=>addToCart(product));return card;}
function renderProducts(products){const hot=[...products].sort((a,b)=>Number(b.amount||0)-Number(a.amount||0)).slice(0,8);const newest=[...products].reverse().slice(0,8);const sale=[...products].filter(product=>Number(product.discount||0)>0).sort((a,b)=>Number(b.discount||0)-Number(a.discount||0)).slice(0,8);const groups={hot,new:newest,sale:sale.length?sale:products.slice(0,8)};Object.entries(groups).forEach(([key,items])=>{grids[key].innerHTML="";items.forEach(product=>grids[key].append(createCard(product)));});}
function addToCart(product){const cart=getCart();const item=cart.find(item=>String(item.id)===String(product.id));const stock=Number(product.amount||0);if(item){if(Number(item.quantity||0)>=stock){showToast(`Số lượng ${product.name} đã đạt mức tối đa.`);return;}item.quantity=Number(item.quantity||0)+1;}else{cart.push({id:product.id,name:product.name||"",image:product.image||"",price:Number(product.price||0),discount:Number(product.discount||0),finalPrice:finalPrice(product),description:product.description||"",distributor:product.distributor||"",amount:stock,quantity:1});}localStorage.setItem("cart",JSON.stringify(cart));showToast(`Đã thêm ${product.name||"sản phẩm"} vào giỏ hàng.`);}
function showToast(message){toastMessage.textContent=message;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),2600);}
async function loadProducts(){showState("Đang tải sản phẩm...");try{const snapshot=await getDocs(collection(db,"products"));const products=snapshot.docs.map(doc=>({id:doc.id,...doc.data()}));if(!products.length){showState("Chưa có sản phẩm nào.");return;}renderProducts(products);}catch(error){console.error(error);showState("Không thể tải sản phẩm. Vui lòng thử lại sau.","error");}}
loadProducts();
